# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine: true

    working_directory: ~/DevFest18

    steps:
      - checkout
      - run: curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
      - run: sudo dpkg -i cf-cli_amd64.deb
      - run: cf -v
      - run: cf api https://api.eu-gb.bluemix.net
      - run: cf auth $BLUEMIX_USER $BLUEMIX_PASSWORD
      - run: cf target -o $BLUEMIX_ORG -s $BLUEMIX_SPACE
      - run: cf a
      - run: cf push